//
//  PostListInteractor.swift
//  VIPPatternPractice
//
//  Created by 강민혜 on 3/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListBusinessLogic
{
  func doSomething(request: PostList.Something.Request)
}

protocol PostListDataStore
{
  //var name: String { get set }
}

class PostListInteractor: PostListBusinessLogic, PostListDataStore
{
  var presenter: PostListPresentationLogic?
  var worker: PostListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PostList.Something.Request)
  {
    worker = PostListWorker()
    worker?.doSomeWork()
    
    let response = PostList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
