//
//  PostListPresenter.swift
//  VIPPatternPractice
//
//  Created by 강민혜 on 3/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListPresentationLogic
{
  func presentSomething(response: PostList.Something.Response)
}

class PostListPresenter: PostListPresentationLogic
{
  weak var viewController: PostListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PostList.Something.Response)
  {
    let viewModel = PostList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
